mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb
  
mysql_databases:
  - name: myproject
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: dbadmin
    host: "%"
    password: dbpassword
    priv: "*.*:ALL"
mysql_user_home: /root
mysql_root_username: root
mysql_root_password: root
mysql_enabled_on_startup: yes
mysql_root_password_update: yes
