---
# Deploy API
- hosts: all
   
  tasks:
  - name: Clone repository
    command: "git clone https://github.com/van-hai-son/myproject.git"
    args:
      chdir: /var/www
      creates: /var/www/myproject

  - name: Composer install
    command: "composer install --prefer-dist --no-interaction"
    args:
      chdir: /var/www/myproject

  - name: Flush Redis
    shell: redis-cli flushall
  
  - name: Dump doctrine
    shell: "php bin/console doctrine:cache:clear-metadata && bin/console doctrine:schema:update --force --dump-sql"
    args:
      chdir: /var/www/myproject

  - name: Create Elasticsearch index
    shell: "php bin/console ongr:es:index:create"
    args:
      chdir: /var/www/myproject

  - name: Clear cache
    shell: "php bin/console cache:clear"
    args:
      chdir: /var/www/myproject

  - name: NPM install
    shell: "npm install"
    args:
      chdir: /var/www/myproject/web/bundle

  - name: Dump Webpack
    shell: "node_modules/.bin/webpack"
    args:
      chdir: /var/www/myproject/web/bundle
